# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Kevin P. Inscoe's future web home
email: kevin.inscoe@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Where I put my public articles
baseurl: "" # Because this is a user site (<username>.github.io), keep baseurl: "". 
# Your pages will be at https://<username>.github.io/....
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  kevinpinscoe

# Build output folder (what GitHub Pages will serve)
destination: docs

# Build settings
theme: minima

header_pages:
  - articles/index.md
  - linux/index.md
  - software/index.md
  - radio/index.md
  - interests/interests.md
  - misc/misc.md

collections:
  articles:
    output: true
    permalink: /:collection/:path/   # => /articles/linux/foo/

plugins:
  - jekyll-feed

# Tell jekyll-feed to generate feed for the 'articles' collection (not posts)
jekyll-feed:
  collections:
    - articles

defaults:
  - scope: { path: "", type: articles }
    values:
      layout: article
      # optionally set a default category by folder; you can also set per-file

# Exclude from processing.
# The following items will not be processed,
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# Don’t read what we write (avoids infinite loops locally)
exclude:
  - docs
  - .git
  - .github
  - .jekyll-cache
  - .bundle
  - vendor
